# name: CI

# #on: [push]

# # 在master分支发生push事件时触发。
# on: 
#   push:
#     branches:
#       - master

# jobs: # 工作流
#   build: # 自定义名称
#     runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps: # 步骤
#       - name: Checkout # 步骤1
#         uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
#       - name: Use Node.js ${{ matrix.node-version }} # 步骤2
#         uses: actions/setup-node@v1 # 作用：安装nodejs
#         with:
#           node-version: ${{ matrix.node-version }} # 版本
#       # - name: run deploy.sh # 步骤3 （同时部署到github和coding）
#       #   env: # 设置环境变量
#       #     VDOING: ${{ secrets.VDOING }} # toKen私密变量
#       #     CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
#       #   run: npm install && npm run deploy

#       # - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
#       #   uses: JamesIves/github-pages-deploy-action@v4 # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
#       #   env: # 设置环境变量
#       #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
#       #     BASE_BRANCH: master # 要部署的文件夹所在的分支.
#       #     BRANCH: gh-pages # 部署到的分支
#       #     FOLDER: docs/.vuepress/dist # 要部署的文件夹.
#       #     BUILD_SCRIPT: npm install && npm run build  && cd docs/.vuepress/dist && echo 'pasregret.com' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vuepress/dist # The folder the action should deploy.
          token: ${{ secrets.ACCESS_TOKEN }}